#!/bin/sh
#SBATCH -p cbuild
#SBATCH -t 2:00:00
#SBATCH --job-name=build_image_apptainer
#SBATCH --output=build_image_apptainer-%j.out

set -e 
export APPTAINER_CACHEDIR=/scratch-shared/azadaianchuk/apptainer_cache
# Create and set temporary directory in scratch space to avoid 'nodev' mount issues
export  APPTAINER_TMPDIR=$(mktemp -d /tmp/${USER}XXXX)

# Note the necessary --fakeroot option
apptainer build --fakeroot /scratch-shared/azadaianchuk/videogen/cosmos/cosmos.sif cosmos.def